# Generated by Django 4.2 on 2023-04-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_events_alter_profiles_phone_event_registion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='poster',
        ),
    ]
