# Generated by Django 4.2 on 2023-04-27 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_events_poster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_registion',
            new_name='Event_registration',
        ),
    ]
