# Generated by Django 4.2 on 2023-04-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_event_registion_event_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='eventdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='lastdatetoreg',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='maxparticipants',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Event_registration',
        ),
    ]
