# Generated by Django 4.2 on 2023-05-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_events_description_events_eventdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='ids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
