# Generated by Django 4.2 on 2023-05-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_specialevents_remove_events_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
